# Generated by Django 5.1 on 2024-08-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_cart_customer_alter_order_customer_and_more'),
        ('product', '0002_alter_product_seller'),
        ('authentication', '0002_customuser_is_customer_customuser_is_seller_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='user',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
